apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-webserver
spec:
  selector:
    matchLabels:
      run: go-webserver
  replicas: 1
  template:
    metadata:
      labels:
        run: go-webserver
    spec:
      containers:
      - name: go-webserver
        image: byroncollins/hpa-example
        ports:
        - containerPort: 8080
        resources:
          limits:
            cpu: 500m
          requests:
            cpu: 200m
---
apiVersion: v1
kind: Service
metadata:
  name: go-webserver
  labels:
    run: go-webserver
spec:
  ports:
  - port: 8080
  selector:
    run: go-webserver